spring:
  profiles:
    active: dev

mybatis:
  config-location: classpath:chat/config/mybatis-config.xml
  mapper-locations: classpath:chat/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true

